from pydantic import BaseModel, Field
from typing import Literal


class LeadProfile(BaseModel):
    """
    Represents the structured analysis of a potential customer lead
    generated by an LLM-based sales qualification system.
    """

    intent_score: int = Field(
        ...,
        ge=1,
        le=10,
        description="Lead intent score between 1 and 10."
    )

    situation_summary: str = Field(
        ...,
        description="Short summary of the lead's current situation."
    )

    urgency: Literal["low", "medium", "high"] = Field(
        ...,
        description="Urgency level of the lead."
    )

    is_first_buyer: bool = Field(
        ...,
        description="Whether the lead is a first-time buyer."
    )

    recommended_approach: str = Field(
        ...,
        description="Suggested sales or communication approach."
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Model confidence score between 0 and 1."
    )